package com.akcreation.gitsilent.constants

import com.github.git24j.core.Oid
import kotlinx.coroutines.sync.Mutex
import java.time.format.DateTimeFormatter

object Cons {
    const val scrollToItemOffset = -2
    const val pushDelayCheckFrquencyInMillSec = 2000L
    const val repoBusyStr = "Repo busy now, plz try again later." ;
    const val itemDetailSpliter = "\n\n--------------\n\n"
    const val oneChar3dots = "…"
    const val isShallowStr = "IsShallow"
    const val notShallowStr = "NotShallow"
    const val httpStr = "Http"
    const val sshStr = "Ssh"
    const val flagStr =  "Flag"
    const val init_last_clicked_item_key =  "nexist_last_clicked_item_key_1899_1253RBCZ" 
    const val ChangeListNaviTarget_InitValue = "cl_navi_init_value"
    const val ChangeListNaviTarget_NoNeedReload = "cl_navi_no_need_reload"  
    const val slash = "/"
    const val slashChar = '/'
    const val lineBreak = "\n"
    const val lineBreakChar = '\n'
    const val arrowToRight = ">"
    const val defaultAllRepoParentDirName = "PuppyGitRepos"
    const val defalutPuppyGitDataUnderAllReposDirName = "PuppyGit-Data"
    const val defaultFileSnapshotDirName = "FileSnapshot"
    const val defaultEditCacheDirName = "EditCache"  
    const val defaultLogDirName = "Log"
    const val defaultSubmoduleDotGitFileBakDirName = "SmGitBak"  
    const val defaultPatchDirName = "Patch"
    const val defaultSettingsDirName = "Settings"
    val defaultDateTimeFormatter:DateTimeFormatter = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss")
    val dateTimeFormatterCompact:DateTimeFormatter = DateTimeFormatter.ofPattern("yyyyMMddHHmmss")
    val dateTimeFormatter_yyyyMMdd:DateTimeFormatter = DateTimeFormatter.ofPattern("yyyyMMdd")
    val dateTimeFormatter_yyyyMMddHHmm:DateTimeFormatter = DateTimeFormatter.ofPattern("yyyyMMddHHmm")
    const val git_AllZeroOidStr = "0000000000000000000000000000000000000000"  
    val git_AllZeroOid: Oid = Oid.of(git_AllZeroOidStr)  
    const val ppgitReservedHashPrefix = "PPGIT_RESERVED_HASH:"
    const val git_LocalWorktreeCommitHash = "${ppgitReservedHashPrefix}LOCAL"  
    const val git_IndexCommitHash = "${ppgitReservedHashPrefix}INDEX"  
    const val git_HeadCommitHash = "HEAD"  
    const val git_DotGitModules = ".gitmodules"
    const val selectedItem_Never = -1 
    const val selectedItem_Repos = 1;
    const val selectedItem_Files = 2;
    const val selectedItem_Editor = 3;
    const val selectedItem_ChangeList = 4;
    const val selectedItem_Settings = 5;
    const val selectedItem_About = 6;
    const val selectedItem_Subscription = 7;
    const val selectedItem_Exit = 8;  
    const val selectedItem_Service = 9
    const val selectedItem_Automation = 10  
    const val errorCantGetExternalFilesDir = "Err: Can't get External files Dir"
    const val errorCantGetExternalCacheDir = "Err: Can't get External cache Dir"
    const val errorCantGetInnerDataDir = "Err: Can't get Inner data Dir"
    const val errorCantGetInnerCacheDir = "Err: Can't get Inner cache dir"
    const val errorCantGetInnerFilesDir = "Err: Can't get Inner files dir"
    const val createDirTestNamePrefix = "test-create_"  
    const val nav_HomeScreen = "home"
    const val nav_CredentialManagerScreen = "credentialman"
    const val nav_CommitListScreen = "commitlist"
    const val nav_ErrorListScreen = "errlist"
    const val nav_CloneScreen = "clone"
    const val nav_DiffScreen = "diff"
    const val nav_IndexScreen = "index"
    const val nav_CredentialNewOrEditScreen = "credential_new_or_edit"
    const val nav_CredentialRemoteListScreen = "credential_remote_list"
    const val nav_BranchListScreen = "branchlist"
    const val nav_TreeToTreeChangeListScreen = "tree_to_tree_changelist"
    const val nav_RemoteListScreen = "remote_list"
    const val nav_SubPageEditor = "subpage_editor"
    const val nav_TagListScreen = "taglist"
    const val nav_ReflogListScreen = "refloglist"
    const val nav_StashListScreen = "stashlist"
    const val nav_SubmoduleListScreen = "submodulelist"
    const val nav_DomainCredentialListScreen = "domain_credential_list"
    const val nav_FileHistoryScreen = "file_history"
    const val nav_FileChooserScreen = "file_chooser"
    const val gitUrlTypeHttp = 1
    const val gitUrlTypeSsh = 2
    const val gitUrlHttpStartStr = "http:
    const val gitUrlHttpsStartStr = "https:
    const val gitAllTagsRefspecForFetchAndPush = "refs/tags
    val checkoutType_checkoutRefThenUpdateHead = 1
    val checkoutType_checkoutRefThenDetachHead=2
    val checkoutType_checkoutCommitThenDetachHead=3
    val zero000Ip = "0.0.0.0"
    val localHostIp = "127.0.0.1"
}
