
#ifndef INCLUDE_git_errors_h__
#define INCLUDE_git_errors_h__
#include "common.h"
GIT_BEGIN_DECL
typedef enum {
	GIT_OK              =  0,
	GIT_ERROR           = -1,
	GIT_ENOTFOUND       = -3,   
	GIT_EEXISTS         = -4,   
	GIT_EAMBIGUOUS      = -5,   
	GIT_EBUFS           = -6,   
	GIT_EUSER           = -7,
	GIT_EBAREREPO       = -8,   
	GIT_EUNBORNBRANCH   = -9,   
	GIT_EUNMERGED       = -10,  
	GIT_ENONFASTFORWARD = -11,  
	GIT_EINVALIDSPEC    = -12,	
	GIT_ECONFLICT       = -13,	
	GIT_ELOCKED         = -14,	
	GIT_EMODIFIED       = -15,	
	GIT_EAUTH           = -16,	
	GIT_ECERTIFICATE    = -17,	
	GIT_EAPPLIED        = -18,	
	GIT_EPEEL           = -19,	
	GIT_EEOF            = -20,	
	GIT_EINVALID        = -21,	
	GIT_EUNCOMMITTED    = -22,	
	GIT_EDIRECTORY      = -23,	
	GIT_EMERGECONFLICT  = -24,	
	GIT_PASSTHROUGH     = -30,	
	GIT_ITEROVER        = -31,	
	GIT_RETRY           = -32,	
	GIT_EMISMATCH       = -33,	
	GIT_EINDEXDIRTY     = -34,	
	GIT_EAPPLYFAIL      = -35,	
	GIT_EOWNER          = -36,	
	GIT_TIMEOUT         = -37,	
	GIT_EUNCHANGED      = -38,	
	GIT_ENOTSUPPORTED   = -39,	
	GIT_EREADONLY       = -40	
} git_error_code;
typedef enum {
	GIT_ERROR_NONE = 0,
	GIT_ERROR_NOMEMORY,
	GIT_ERROR_OS,
	GIT_ERROR_INVALID,
	GIT_ERROR_REFERENCE,
	GIT_ERROR_ZLIB,
	GIT_ERROR_REPOSITORY,
	GIT_ERROR_CONFIG,
	GIT_ERROR_REGEX,
	GIT_ERROR_ODB,
	GIT_ERROR_INDEX,
	GIT_ERROR_OBJECT,
	GIT_ERROR_NET,
	GIT_ERROR_TAG,
	GIT_ERROR_TREE,
	GIT_ERROR_INDEXER,
	GIT_ERROR_SSL,
	GIT_ERROR_SUBMODULE,
	GIT_ERROR_THREAD,
	GIT_ERROR_STASH,
	GIT_ERROR_CHECKOUT,
	GIT_ERROR_FETCHHEAD,
	GIT_ERROR_MERGE,
	GIT_ERROR_SSH,
	GIT_ERROR_FILTER,
	GIT_ERROR_REVERT,
	GIT_ERROR_CALLBACK,
	GIT_ERROR_CHERRYPICK,
	GIT_ERROR_DESCRIBE,
	GIT_ERROR_REBASE,
	GIT_ERROR_FILESYSTEM,
	GIT_ERROR_PATCH,
	GIT_ERROR_WORKTREE,
	GIT_ERROR_SHA,
	GIT_ERROR_HTTP,
	GIT_ERROR_INTERNAL,
	GIT_ERROR_GRAFTS
} git_error_t;
typedef struct {
	char *message;  
	int klass;      
} git_error;
GIT_EXTERN(const git_error *) git_error_last(void);
GIT_END_DECL
#endif
